[package]
name = "poison-studio-style"
version = "0.1.0"
description = "WolvDoesStuff Portfolio and Bot"

[dependencies]
"wasmer/node" = "20"

[command.start]
cmd = "node discord-bot.js"
runner = "https://webc.org/runner/node"

[fs]
"/dist" = "dist"