[package]
name = "portfolio"
version = "1.0.0"
description = "Portfolio website"

[fs]
"/public" = "dist"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/public"]
